### ISSUE TITLE
No support for AGP >= 4.2 on Android

### ISSUE THREAD

**Issue by Johan-glitch1412** [Heewookji/gtm#10]
Hi, we are trying to upgrade our gradle and android versions on our app, but we see that this package does not support the namespace change as of yet.

It is luckily a very simple change inside of the android/app/build.gradle.

The following code needs to be added in the android scope:
```
// Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'kr.heewook.gtm_android'
    }
```
I can create a pull request if that would help?

**Comment by Johan-glitch1412** [comment]
It seems like I can only pull though, it does not look like I can push any new branches. I tried to push to fix/agp-latest and I don't have the necessary permissions to do so

**Comment by Heewookji** [comment]
Hi! i have merged your branch and updated it in pub as well.
It seems to be working fine, but if you find any issues please let me know.
Thanks for your contribution.

**Comment by Heewookji** [comment]
Hi! i have merged your branch and updated it in pub as well.
It seems to be working fine, but if you find any issues please let me know.
Thanks for your contribution.
