### ISSUE TITLE
Missing plugin exception is occuring

### ISSUE THREAD

**Issue by salahvk** [Heewookji/gtm#12]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method push on channel heewook.kr/gtm_android)
 
Missing plugin exception is occuring even though i do flutter clean , restarted project ,added  (implementation 'com.google.android.gms:play-services-tagmanager:18.0.4') in app/build.gradle file ,added containers json file in android/src/main/assets/containers

![image](https://github.com/Heewookji/gtm/assets/88548221/3b2ae16a-6d27-441e-abcf-2e5c0077058e)

**Comment by Heewookji** [comment]
It seems that the Android plugin requires google-service dependency.
I think this happened because in the past, the dependency was explicitly required when configuring firebase, 
but with recent configuration through `flutterfire configure`, it is no longer needed.
So, it will be solved by adding the corresponding code as in the example below.

```gradle
// android/build.gradle
dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.14' // add
}
```
```gradle
// android/app/build.gradle
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}
apply plugin: 'com.google.gms.google-services' // add
```

I'll think of a way that doesn't require google-service dependency.
Let me know if you have any other problems.

**Comment by salahvk** [comment]
Tried the solution but its not working, same issue is occurring,
I am using the latest version of flutter [3.19.5]

Nb :- in the latest version of flutter there is little bit changes in all three gradle files, 
https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
I used both the gradle methods still not working (before breaking change and after)
is it because of flutter version

**Comment by Heewookji** [comment]
I created a new project with version 3.19.5 and tested it, and it worked normally.

Below is an example of the yaml file I modified in the project, app/build.gradle. 
In addition to this modification, I set the Android project to firebase through flutterfire configure, 
and the push method worked without error.(Even without applying the temporary measures mentioned above)
If there is no problem with your settings, can you send me an example project where the error occurs?

```yaml
gtm: ^0.1.3
firebase_core: ^2.27.0
firebase_analytics: ^10.8.9
```
```gradle
// app/build.gradle
defaultConfig {
  minSdkVersion 23 
  targetSdkVersion 33
```

**Comment by salahvk** [comment]
Thank You Heewookji !
Sorted the issue , 
*Google service  version i used was 4.4.1 ( id "com.google.gms.google-services" version "4.4.1" apply false ) which i changed to 4.3.15 , its the default version adding automatically by configuring flutter fire cli , also after removing all the configuration and setting up cli from scratch fixed the issue
