### ISSUE TITLE
Add option to disable console logs?

### ISSUE THREAD

**Issue by ken717w** [Heewookji/gtm#13]
Right now a lot of log `GoogleTagManager info: Processing logged event: XXXXX` are flooding around in console, makes it hard to see other debug messages during development.

It would be nice to have such option, like a silent mode? What do you think?
Cheers.

**Comment by Heewookji** [comment]
Published version 0.1.5, which includes the hideInfoLog method.
Since Android doesn't output logs by default, it will only affect iOS behavior.
Cheers.
