### ISSUE TITLE
How does this lib work?

### ISSUE THREAD

**Issue by benjaminclot** [Heewookji/gtm#16]
Hi,

I'm reading through the source code, and even though I can see events in Analytics realatime Debug (sometimes), I don't quite understand how it works, because I don't see any Google endpoint being invoked.
Can you provide an explanation please? I'm using it on Android.

Thanks!

**Comment by Heewookji** [comment]
Hi!
As written in the [document](https://pub.dev/packages/gtm), Firebase Analytics serves as the data layer.
So when you pushing an event using gtm plugin, firebaseAnalytics.logEvent is called internally.
You can find code in GtmAndroidPlugin.kt (gtm_android plugin).

**Comment by benjaminclot** [comment]
Thank you! It's much more clear now :)
