### ISSUE TITLE
GTM is not recording any events

### ISSUE THREAD

**Issue by dineshnaikb** [Heewookji/gtm#18]
@Heewookji 

E/flutter ( 9363): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method push on channel heewook.kr/gtm_android)
E/flutter ( 9363): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter ( 9363): <asynchronous suspension>
E/flutter ( 9363): #1      GtmAndroid.push (package:gtm_android/src/gtm_android.dart:36:20)
E/flutter ( 9363): <asynchronous suspension>

  gtm: ^1.0.0

    id "com.android.application" version "7.3.1" apply false
    id "org.jetbrains.kotlin.android" version "2.0.20" apply false
    id "com.google.gms.google-services" version "4.4.2" apply false

**Comment by Heewookji** [comment]
Try the solutions below and let me know if they don't resolve the issue.
https://github.com/Heewookji/gtm/issues/1#issuecomment-1499892163
