### ISSUE TITLE
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/ios/Pods/GoogleTagManager/Frameworks/GoogleTagManager.xcframework)

### ISSUE THREAD

**Issue by taskindrp** [Heewookji/gtm#2]
Hello,

Error when building the app.

```
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/ios/Pods/GoogleTagManager/Frameworks/GoogleTagManager.xcframework)
```

found this issue comment https://github.com/flutter/flutter/issues/15031#issuecomment-380235326 can adding `s.static_framework = true` to https://github.com/Heewookji/gtm/blob/main/gtm_ios/ios/gtm_ios.podspec resolve the issue?

**Comment by Heewookji** [comment]
Hi, @taskindrp !
Could you show me the contents of the `Project/ios/Podfile`? I'll try to reproduce it and let you know.

**Comment by taskindrp** [comment]
> Hi, @taskindrp ! Could you show me the contents of the `Project/ios/Podfile`? I'll try to reproduce it and let you know.

```
$FirebaseAnalyticsWithoutAdIdSupport = true
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

**Comment by Heewookji** [comment]
`use_frameworks!` -> `use_frameworks! :linkage => :static`

let me know if this fix fixed the problem

**Comment by Heewookji** [comment]
I'll check the part about `s.static_framework` and apply it.

Until then, would you like to do the following?

`use_frameworks!` -> `use_frameworks! :linkage => :static`

**Comment by taskindrp** [comment]
> I'll check the part about s.static_framework and apply it.

I have forked the project here https://github.com/taskindrp/gtm and applied `s.static_framework`, it solved the issue.

**Comment by Heewookji** [comment]
> > I'll check the part about s.static_framework and apply it.
> 
> I have forked the project here https://github.com/taskindrp/gtm and applied `s.static_framework`, it solved the issue.

Thanks for checking! 
It was added in 0.0.7 version, so check it out and reopen if there are any problems.
