### ISSUE TITLE
GTM version 1.0.1 not working

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [Heewookji/gtm#23]
Note: Recompile with -Xlint:unchecked for details.
e: file:///Users/hieucg/.pub-cache/hosted/pub.dev/gtm_android-0.1.3/android/src/main/kotlin/kr/heewook/gtm_android/GtmAndroidPlugin.kt:51:21 Backing field of 'var channel: MethodChannel' is not accessible at this point.

**Comment by TeD0R** [comment]
Same issue

**Comment by poka-IT** [comment]
same issue here

**Comment by ANMARBA** [comment]
same issue here
