### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by rishabhsharma3617** [Heewookji/gtm#5]
Is this package only works for sending events to GTM -> Google Analytics , cant we utilise it for any other third party like GTM -> Mixpanel , webengage etc .

**Comment by Heewookji** [comment]
You can use any third party tags you want. 
For example, if you want to use a mixpanel you can write the code below.

```dart
final _mixpanel = await Mixpanel.init('mixpanelProjectToken', trackAutomaticEvents: true);

_gtm.setCustomTagTypes([
        CustomTagType(
          'mixpanel', // you need to set this tagType at gtm container
          handler: (eventName, parameters) {
            _mixpanel.track(
              eventName,
              properties: parameters,
            );
          },
        ),
      ]);
```

For more details about CustomTag, please refer to [this link
](https://pub.dev/packages/gtm#customtag)
